name: README

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: purcell/setup-emacs@master
        with:
          version: 28.2
      - run: scripts/readme
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Regenerate README.md
